### ISSUE TITLE
Checklist final p/ release dos anos 2017, 2018 e 2019

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#122]
- [x] Terminar de rodar ttmatrix p/ ano de 2019 Sâo Paulo (constantemente dando problema, seção do R dá crash etc)
- [x] Concluir matrizes de carro e fazer rápida checagem pra ver se todos os pontos estão OK @diegobt86 
- [x] Rodar script para correção das matrizes de transporte público/caminhada/bicicleta p/ 2017, 2018 e 2019;
- [x] Calcular acessibilidade para todos os anos e modos;
- [x] Fazer checagem final dos valores de uso do solo e acessibilidade; #121 e #119 estão relacionadas;
- [x] Consolidar base final; #116 e #117 estão relacionados
