### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#36]
- [x] Rodar matrizes novamente para `man` e `cgr`;
- [x] Atualizar os mapas do TD com os tiles do ceramic;
- [x] Trabalhar na conclusão do TD
