### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#37]
- [x] 1) Organizar scripts 5 (figuras)

Organizar base de dados para publicação
- [x] 2) Corrigir a quantidade de equipamento total de saúde no script 02.3;
- [x] 3) Organizar DF com colunas selecionadas; 
- [x] 4) Organizar dicionario de variaveis (PORT e ING)

Side:
- [ ] 5) proposta de artigo: "The racial and economic inequalities in access to health services in Brazil"

depois.... colaboracao Venter

**Comment by kauebraga** [comment]
Resolvido 1) em https://github.com/ipeaGIT/acesso_oport/commit/7ef275586db9f8450442eefcea013b03e2975a29

**Comment by kauebraga** [comment]
Resolvido 2) em https://github.com/ipeaGIT/acesso_oport/commit/fc4b5e12d7c773ba1efc1c41aeb99a0c9f682210

**Comment by kauebraga** [comment]
Resolvido 3) em https://github.com/ipeaGIT/acesso_oport/commit/74aeb660c9a92d88691f72dbd1d77e32b98f17cf

**Comment by rafapereirabr** [comment]
> Resolvido 3) em [74aeb66](https://github.com/ipeaGIT/acesso_oport/commit/74aeb660c9a92d88691f72dbd1d77e32b98f17cf)
> 
> Porém, alguns pontos ainda para discussão:
> 
> * Devemos separar bases diferentes por modo (tp e ativo)?
> * Devemos separar as bases por uso do solo e acessibilidade?
>   _+ Essa separação evita confusão e repetição das variáveis para mais de um hexágono, por ex

Em principio, acho que o ideal seria que a cada ano a gente disponibilizasse uma base unica cobrindo todas cidades, modos, usos do solo, pico, fora pico etc etc. Dai eh deixar claro na documentacao que sao dados empilhados. Em geral, que usa microdado tem (ou deveria ter) conhecimento experiencia para lidar com isso :)

**Comment by kauebraga** [comment]
Beleza! O único problema de colocar os modos juntos é que vão ter colunas NA quando aquele threshold não foi calculado praquele modo. Ex para Belém:

| CMAEI60| CMAEF60| CMAEM60| CMATT90| CMATQ90| CMATD90| CMAST90|
|-------:|-------:|-------:|-------:|-------:|-------:|-------:|
|   0.082|   0.064|   0.060|      NA|      NA|      NA|      NA|
|   0.055|   0.028|   0.026|      NA|      NA|      NA|      NA|
|   0.091|   0.067|   0.060|      NA|      NA|      NA|      NA|
|   0.055|   0.028|   0.026|      NA|      NA|      NA|      NA|
|   0.073|   0.060|   0.060|      NA|      NA|      NA|      NA|
|   0.055|   0.028|   0.026|      NA|      NA|      NA|      NA|
|   0.082|   0.064|   0.060|      NA|      NA|      NA|      NA|
|   0.055|   0.028|   0.026|      NA|      NA|      NA|      NA|
|   0.055|   0.035|   0.026|      NA|      NA|      NA|      NA|
|   0.036|   0.018|   0.026|      NA|      NA|      NA|      NA|

**Comment by rafapereirabr** [comment]
item (4) resolvido

**Comment by rafapereirabr** [comment]
moving item (5) to another issue
